Ecommerce/ecommerce_project/cart_app/urls.py
from django.urls import path
from .import views
app_name='cart_app'

urlpatterns=[
    path('',views.cart_detail,name='cart_detail'),
    path('add/<product_id>/',views.add_to_cart,name='add_to_cart'),
    path('remove/<int:product_id>/',views.remove_from_cart,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.remove_full,name='full_remove')
]

Ecommerce/ecommerce_project/ecommerce_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views
app_name='ecommerce_app'
urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='Products_by_category'),
    path('<slug:c_slug>/<slug:p_slug>/',views.ProductDetails,name='Product_details'),
    # path('',include('ecommerce_app.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Ecommerce/ecommerce_project/ecommerce_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
     path('ecommerce',include('ecommerce_app.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart_app.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Ecommerce/ecommerce_project/search_app/urls.py
from .import views
from django.urls import path,include
app_name='search_app'

urlpatterns=[
    path('',views.search,name='search'),
]

Ecommerce/ecommerce_project/cart_app/models.py
from django.db import models
from ecommerce_app.models import Product



# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        # return self.cart_id
        return '{}'.format(self.cart_id)
class CartItems(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItems'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        # return self.product
        return '{}'.format(self.product)

Ecommerce/ecommerce_project/ecommerce_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.



class Category(models.Model):
    cname=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    cdescription=models.TextField(blank=True)
    cimage=models.ImageField(upload_to='category',blank=True)
    class Meta:
        ordering=('cname',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse('ecommerce_app:Products_by_category',args=[self.slug])
    def __str__(self):
        return '{}'.format(self.cname)
class Product(models.Model):
    pname=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    pdescription=models.TextField(blank=True)
    pimage=models.ImageField(upload_to='product',blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now=True)

    def get_url(self):
        return reverse('ecommerce_app:Product_details',args=[self.category.slug,self.slug])
    class Meta:
        ordering=('pname',)
        verbose_name='product'
        verbose_name_plural='products'
    def __str__(self):
        return '{}'.format(self.pname)

Ecommerce/ecommerce_project/search_app/models.py
from django.db import models

# Create your models here.

Ecommerce/ecommerce_project/cart_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerce_app.models import Product
from .models import Cart, CartItems
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()

    return cart


def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))

    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItems.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItems.DoesNotExist:
        cart_item = CartItems.objects.create(product=product, quantity=1, cart=cart)
        cart_item.save()
    return redirect('cart_app:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItems.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items, total=total, counter=counter))
def remove_from_cart(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItems.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart_app:cart_detail')
def remove_full(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItems.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart_app:cart_detail')

Ecommerce/ecommerce_project/ecommerce_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Product,Category
from django.core.paginator import Paginator,EmptyPage,InvalidPage,PageNotAnInteger

# Create your views here.
# def home(request):
#     return HttpResponse('hi ecommerce app')
def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)

    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page',1))
        # page = int(request.GET.get('page'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    # page = request.GET.get('page')
    # try:
    #     products = paginator.page(page)
    # except PageNotAnInteger:
    #     # If page is not an integer, deliver the first page.
    #     products = paginator.page(1)
    # except (EmptyPage,InvalidPage):
    #     # If page is out of range (e.g., 9999), deliver the last page.
    #     products = paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})
def ProductDetails(request,c_slug,p_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=p_slug)

    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

Ecommerce/ecommerce_project/search_app/views.py
from django.shortcuts import render
from ecommerce_app.models import Product
from django.db.models import Q


# Create your views here.
def search(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(pname__contains=query) | Q(pdescription__contains=query))


    return render(request,'search.html',{'products':products,'query':query})

Ecommerce/ecommerce_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<!--<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>-->
<!--<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@1,100&display=swap" rel="stylesheet">-->

    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@1,100;1,400&display=swap" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >-->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">


<!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/e17832e81a.js" crossorigin="anonymous"></script>

    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
    <br>
    <br>

{% block content %}
{% endblock %}
</div>

{% include 'footer.html' %}
<!--<script src=" {% static 'js/popper.min.js' %}" ></script>-->
<!--<script src="{% static 'js/bootstrap.min.js' %}"></script>-->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

Ecommerce/ecommerce_project/templates/cart.html
{% extends 'base.html'%}
{% load static %}
{% block metadescription %}
    Cart Page,Review items and Place the order.
{% endblock %}
{% block title %}
    Cart-Amaan the complete
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title"> Your Cart is Empty</h1>
        <br>
        <p class="text-center">Please click <a href="{% url 'ecommerce_app:allProdCat' %}">Here</a>to continue shopping !!!</p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <h1 class="text-center my_title"><b>Your Cart</b></h1>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                        <b>Your Items</b>
                    </th>
                </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="{{ cart_item.product.get_absolute_url}}"><img src="{{cart_item.product.pimage.url}}" alt="" style="width:100px;height:100px;" class="float-left rounded custom_image "></a>
                    </td>
                    <br>
                    <td class="text-left">
                        {{ cart_item.product.pname}}
                        <br>
                        SKU:{{cart_item.product.id}}
                         <br>
                        Price:Rs {{cart_item.product.price}}
                        <br>
                        Qty:{{cart_item.quantity}}x{{cart_item}}
                    </td>
                    <td>
                        Rs {{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart_app:add_to_cart' cart_item.product.id %}" class="custom-a"><i class="fa-solid fa-plus"></i></a>
                        &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus"></i></a>
                        &nbsp;<a href=" {% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash custom_icon" ></i></a>
                    </td>
                    {% else %}
                    <td>
                         <a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus"></i></a>
                        &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %} " class="custom_icon"><i class="fa-solid fa-trash custom_icon" ></i></a>
                    </td>
                    {% endif %}
                </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6  text-center">
        <table class="my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                        <b>Check Out</b>
                    </th>
                </tr>
            </thead>
            <br>
            <tbody >
                <tr>
                    <td>
                        <br>
                    Please review your cart items before proceeding to checkout
                    </td>
                </tr>
                <br>
                <tr>
                    <td class="text-center">
                        <br>
                        Your Total amount is : <strong>{{total}}</strong>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'ecommerce_app:allProdCat'%}" class="btn btn-secondary btn-block my_custom_button text-center ">Continue Shopping</a>
        </div>
        <br>
    </div>
</div>

{% endif %}
{% endblock %}

Ecommerce/ecommerce_project/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category  %}
        {{category.cdescription|truncatewords:155 }}
    {% else %}
        Welcome to amaan the complete store.You can flower your needs.
    {% endif %}
{% endblock %}
{% block title %}
    {% if category  %}
        {{category.cname }}----Amaan the complete
    {% else %}
        Welcome to new collections.
    {% endif %}
{% endblock %}
{% block content %}

{% if category  %}
<div>
    <div class="row my_row">
        <div class="mx-auto">
        <p><a href="{% url 'ecommerce_app:allProdCat' %}" >Our product collections </a></p>
        </div>
    </div>
</div>
{% endif  %}

<div class="mx-auto">
    {% if category  %}
    <h1 class="text-center my_title">{{category.cname}}</h1>
    <img class="product_image product_image_padding" src="{{ category.cimage.url}}"alt="{{category.cname}}">
</div>
    <br>


<div>
    <p class="text-justify">{{category.cdescription}}</p>
</div>
    {% else %}
<div>
<img  src="{% static 'images/banner.png'%}" alt="OUR Products" height="320" width="100%">
</div>
<br>
<div>
    <h1 class="text-center my_title">Our Product collection</h1>
    <p class="text-justify">Clothing is any item worn on the body. Typically, clothing is made of fabrics or textiles, but over time it has included garments made from animal skin and other thin sheets of materials and natural products found in the environment, put together.Clothing is also worn for decoration, as a fashion. People from different cultures wear different clothing, and have different beliefs and customs about what type of clothing should be worn. For many people, clothing is a status symbol. It helps people project an image. Often, clothing is a form of self-expression. Adults in different social or work situations present different views of themselves by the clothes they wear. Young people have an entirely different form of dress to express their personalities. Often people will simply follow popular fashion styles so that they will fit in. Clothing is far more than just a means to protect our bodies.
</div>
{% endif %}


<div>
    <div class="container">

        <div class="row mx-auto">

            {% for product in products.object_list %}
            <div class="my_bottom_margin col-9 col-sm-12  col-md-4 col-lg-4" >
                <br>

                <div class="card" style="width: 18rem;">
                <a href="{{ product.get_url }}"><img class="card-img-top product_image" src="{{ product.pimage.url }}" alt="{{ product.pname }}"></a>
                <div class="card-body">
                <h4 class="card-title">{{product.pname}}</h4>
                <p class="card-text">{{product.price}}</p>
                </div>
                </div>
            </div>
            {% endfor %}
            <br>
        </div>

        <div class="mx-auto">

            {% if products.paginator.num_pages > 1 %}
            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %} ">{{pg}}</a>
                {% endfor %}

            </div>
            {% endif %}

        </div>
        <br>
    </div>
</div>
{% endblock %}

Ecommerce/ecommerce_project/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <center>
  <p>&copy; Amaan pvt ltd.All rights are reserved</p>
  </center>
</div>

Ecommerce/ecommerce_project/templates/header.html
{% load static %}
<header>
    <center>
        <br>
    <a href="{% url 'ecommerce_app:allProdCat' %}"><img src="{% static 'images/logo.png' %}" alt="LOGO" width="150px" height="150" ></a>
    </center>
</header>

Ecommerce/ecommerce_project/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#" style="font-family:Lucida Handwriting">Amaan</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">


        <li class="nav-item dropdown {% if 'ecommerce_app' in request.path %} active {% endif %} ">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Products
          </a>
          <ul class="dropdown-menu" >
            <li><a class="dropdown-item" href="{% url 'ecommerce_app:allProdCat'  %}">All Products</a></li>
             {% for cat in links %}
            <li><a class="dropdown-item" href="{{ cat.get_url }}">{{cat.cname}}</a></li>
            {% endfor %}

          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart_app:cart_detail' %}"><i class="fa-solid fa-cart-arrow-down">({{item_count}})</i></a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart_app:cart_detail' %}"><i class="fa-solid fa-cart-arrow-down"></i></a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" role="search" action="{% url 'search_app:search' %}" method="GET">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-dark" type="submit"> <i class="fa-brands fa-searchengin"></i></button>
      </form>
    </div>
  </div>
</nav>

Ecommerce/ecommerce_project/templates/product.html
{% extends 'base.html'%}
{% load static %}
{% block metadescription %}
    {% if product %}
        {{product.pdescription|truncatewords:155 }}

    {% endif %}
{% endblock %}
{% block title %}
    {% if product %}
        {{product.pname }}

    {% endif %}
{% endblock %}
{% block content %}
<div class="row my_product_row">
    <div class="mx-auto">
        <p><a href=" {% url 'ecommerce_app:allProdCat' %}"> Home </a> | <a href="{{ product.category.get_url }}">{{product.category}}</a> | {{ product.pname }}</p>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width:18rem;">
            <img src="{{ product.pimage.url}}" alt="{{ product.name}}">
            </div>
        </div>


        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h4 class="my_prod_title">{{product.name}}</h4>
            <p>₹ {{product.price}}</p>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_prod_desc">{{product.pdescription}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_desc"><b>Out of Stock </b></p>
            {% else %}
            <a class="btn btn-success" href="{% url 'cart_app:add_to_cart' product.id %}">Add to cart</a>
            {% endif %}
            </div>
        </div>
</div>
        <br>


    </div>



{% endblock %}

Ecommerce/ecommerce_project/templates/search.html
{% extends 'base.html'%}
{% load static %}
{% block metadescription %}
    We are having variety collections


{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for <b>"{{query}}"</b></p>
</div>
<div>
    <div class="container">

        <div class="row mx-auto">

            {% for product in products %}
            <div class="my_bottom_margin col-9 col-sm-12  col-md-4 col-lg-4" >
                <br>

                <div class="card" style="width: 18rem;">
                <a href="{{ product.get_url }}"><img class="card-img-top product_image" src="{{ product.pimage.url }}" alt="{{ product.pname }}"></a>
                <div class="card-body">
                <h4 class="card-title">{{product.pname}}</h4>
                <p class="card-text">{{product.price}}</p>
                </div>
                </div>
            </div>
            {% empty %}
            <div class="row mx-auto">
                <p class="text-center my_search_text">0 results </p>
            </div>
            {% endfor %}
            <br>
        </div>
    </div>
</div>
{% endblock %}